# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5/WithDesigner/ComboBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGet = QtWidgets.QPushButton(self.centralwidget)
        self.btnGet.setGeometry(QtCore.QRect(570, 30, 131, 51))
        self.btnGet.setObjectName("btnGet")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(160, 260, 611, 221))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 20, 371, 61))
        self.comboBox.setObjectName("comboBox")
        self.btnSubmit_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit_2.setGeometry(QtCore.QRect(570, 90, 131, 51))
        self.btnSubmit_2.setObjectName("btnSubmit_2")
        self.btnGet_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnGet_2.setGeometry(QtCore.QRect(720, 30, 131, 51))
        self.btnGet_2.setObjectName("btnGet_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGet.setText(_translate("MainWindow", "Get Item"))
        self.btnSubmit_2.setText(_translate("MainWindow", "Load Items"))
        self.btnGet_2.setText(_translate("MainWindow", "Clear Items"))
