# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5/WithDesigner/RadioButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grpbox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbox1.setGeometry(QtCore.QRect(160, 80, 241, 221))
        self.grpbox1.setObjectName("grpbox1")
        self.radioButton = QtWidgets.QRadioButton(self.grpbox1)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.grpbox1)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 70, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.grpbox1)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 110, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.grpbox1)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 140, 95, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.grpbox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbox2.setGeometry(QtCore.QRect(490, 80, 241, 221))
        self.grpbox2.setObjectName("grpbox2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.grpbox2)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 140, 95, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.grpbox2)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.grpbox2)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 110, 95, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.grpbox2)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 70, 95, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit.setGeometry(QtCore.QRect(390, 330, 131, 51))
        self.btnSubmit.setObjectName("btnSubmit")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(240, 400, 431, 191))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpbox1.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton.setText(_translate("MainWindow", "1"))
        self.radioButton_2.setText(_translate("MainWindow", "2"))
        self.radioButton_3.setText(_translate("MainWindow", "3"))
        self.radioButton_4.setText(_translate("MainWindow", "4"))
        self.grpbox2.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton_5.setText(_translate("MainWindow", "44"))
        self.radioButton_6.setText(_translate("MainWindow", "11"))
        self.radioButton_7.setText(_translate("MainWindow", "33"))
        self.radioButton_8.setText(_translate("MainWindow", "22"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))
