# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5/Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(250, 40, 71, 41))
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setGeometry(QtCore.QRect(250, 80, 71, 41))
        self.lbl2.setObjectName("lbl2")
        self.txt1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt1.setGeometry(QtCore.QRect(340, 50, 141, 31))
        self.txt1.setObjectName("txt1")
        self.txt2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt2.setGeometry(QtCore.QRect(340, 90, 141, 31))
        self.txt2.setObjectName("txt2")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(230, 130, 141, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.BtnSubstract = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSubstract.setGeometry(QtCore.QRect(390, 130, 141, 31))
        self.BtnSubstract.setObjectName("BtnSubstract")
        self.btnMultiply = QtWidgets.QPushButton(self.centralwidget)
        self.btnMultiply.setGeometry(QtCore.QRect(390, 180, 141, 31))
        self.btnMultiply.setObjectName("btnMultiply")
        self.BtnDivide = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDivide.setGeometry(QtCore.QRect(230, 180, 141, 31))
        self.BtnDivide.setObjectName("BtnDivide")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(320, 250, 71, 41))
        self.lblResult.setObjectName("lblResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl1.setText(_translate("MainWindow", "Number1: "))
        self.lbl2.setText(_translate("MainWindow", "Number2: "))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.BtnSubstract.setText(_translate("MainWindow", "-"))
        self.btnMultiply.setText(_translate("MainWindow", "*"))
        self.BtnDivide.setText(_translate("MainWindow", "/"))
        self.lblResult.setText(_translate("MainWindow", "Result:"))
