# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt5/WithDesigner/Checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grpbox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbox1.setGeometry(QtCore.QRect(160, 70, 241, 221))
        self.grpbox1.setObjectName("grpbox1")
        self.checkBox = QtWidgets.QCheckBox(self.grpbox1)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.grpbox1)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.grpbox1)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.grpbox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpbox2.setGeometry(QtCore.QRect(490, 80, 241, 221))
        self.grpbox2.setObjectName("grpbox2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.grpbox2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.grpbox2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 90, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.grpbox2)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 60, 81, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit.setGeometry(QtCore.QRect(390, 320, 131, 51))
        self.btnSubmit.setObjectName("btnSubmit")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(260, 400, 401, 151))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpbox1.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox.setText(_translate("MainWindow", "1"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.grpbox2.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox_4.setText(_translate("MainWindow", "11"))
        self.checkBox_5.setText(_translate("MainWindow", "33"))
        self.checkBox_6.setText(_translate("MainWindow", "22"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))
